### ISSUE TITLE
Add support for boto client config to KMSMasterKeyProvider

### ISSUE THREAD

**Issue by mpaolini** [aws/aws-encryption-sdk-python#136]
I came across this limitation while trying to configure encryption sdk to use an http proxy to access the KMS api.

It looks like there is no (documented) way to pass the `config` parameter to the `boto3.client` that is instaciated here 
https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/key_providers/kms.py#L167

my (ugly) workaround is

```python
key_provider = aws_encryption_sdk.KMSMasterKeyProvider()
key_provider._user_agent_adding_config = key_provider._user_agent_adding_config.merge(
    botocore.config.Config(proxies={'http': 'http://example.com'})
)
key_provider._regional_clients.clear()  # needed as the default region client is created in __init__

# This will now use the proxy 
aws_encryption_sdk.decrypt(source=f.read(), key_provider=key_provider)
```

**Comment by mattsb42-aws** [comment]
Thanks for reaching out, @mpaolini 

I think that this, #52, and #137 are all different sides of the same problem: being able to control the creation of the regional clients.

I've been thinking on this, and I think what might make sense is a client generator of some sort that would be used by the KMS MK/P to generate the clients they need.

We would need to retain a couple characteristics:
1. Each client should be made from a new `boto3` session to avoid threading issues.
1. We need to be able to add our useragent to the client config for each client (or at least, we need to make it simple for users to modify any other configuration while retaining this).

In addition to the above, we would need a few configuration points:
1. Either provide a `botocore` session or a way to build a new `botocore` session.
1. Provide a way to build additional kwargs to pass to a new `boto3` session. I'm thinking kwargs rather than just a way to build a new `boto3` session because we want to make it simple to modify the other configuration values while still using the above `botocore` session.
1. Provide a way to build kwargs to pass to a new `kms` client. Similar to above reason for kwargs for the `boto3` session, but also because we want to be able to modify the client config to include our user agent.

If we key on the key ID rather than the region, we can also get the added benefit of providing a more natural extension point for cases where customers might be working with different credentials for different keys.

We would want to use this for both the master key and provider.

Rough sketch, I'm thinking something along these lines:
```python
@attr.s
class KmsClientGenerator(object):
    _botocore_session = attr.ib(
        default=attr.Factory(botocore.session.Session),
        validator=optional(instance_of(botocore.session.Session)),
    )
    _boto3_kwargs = attr.ib(
        default=attr.Factory(dict),
        validator=instance_of(dict),
    )
    _kms_kwargs = attr.ib(
        default=attr.Factory(dict),
        validator=instance_of(dict),
    )

    def botocore_session(self, key_id):
        """PREFERRED EXTENSION POINT"""
        return self._botocore_session

    def boto3_session_kwargs(self, key_id):
        """PREFERRED EXTENSION POINT"""
        kwargs = self._boto3_kwargs.copy()
        if "region_name" not in kwargs:
            kwargs["region_name"] = _region_from_key_id(key_id)
        return kwargs

    def kms_client_kwargs(self, key_id):
        """PREFERRED EXTENSION POINT"""
        return self._kms_kwargs.copy()

    def boto3_session(self, key_id):
        kwargs = self.boto3_session_kwargs(key_id)
        botocore_session = self.botocore_session(key_id)
        return boto3.session.Session(
            botocore_session=botocore_session,
            **kwargs
        )

    def _config_from_kwargs(self, kwargs):
        try:
            config = kwargs["config"]
        except KeyError:
            return botocore.config.Config(user_agent_extra=USER_AGENT_SUFFIX)

        if USER_AGENT_SUFFIX not in config.user_agent_extra:
            config.user_agent_extra += " {suffix}".format(suffix=USER_AGENT_SUFFIX)

        return config

    def kms_client(self, key_id):
        boto3_session = self.boto3_session(key_id)
        kwargs = self.kms_client_kwargs(key_id)
        kwargs["config"] = self._config_from_kwargs(kwargs)
        return boto3_session("kms", **kwargs)
```

With such a system, in your case what you would need to pass in to the MK/P is:

```python
client_generator = KmsClientGenerator(
    kms_kwargs=dict(config=botocore.config.Config(proxies={"http": "http://example.com"}))
)
master_key_provider = KMSMasterKeyProvider(
    key_ids=[key_1, key_2],
    client_generator=client_generator,
)
```

**Comment by farleyb-amazon** [comment]
Given that keyrings are our long-term solution here, I expect that we will not backport this functionality to master key providers. Resolving.
