### ISSUE TITLE
[Feature Request] Parallel master key encryption

### ISSUE THREAD

**Issue by polamayster** [aws/aws-encryption-sdk-python#191]
Can GenerateDataKey call be implemented in concurrent/asynchronous or even non-blocking way for KMSMasterKeyProvider with multiple master keys due to cross-regional latency that tremendously impacts response time?

Please see X-Ray snapshot bellow and pay attention to calls duration:
![aws_encryption_sdk_multiregion](https://user-images.githubusercontent.com/3791902/65172375-6e5a5580-da55-11e9-841a-8f4a16d4af6e.png)

**Comment by mattsb42-aws** [comment]
Hi @polamayster,

That would be possible, yes, though it is not something that we will be changing about the specific behavior of `KMSMasterKeyProvider`.

Instead, we're working on building out a new, simpler, configuration framework on the "keyring" branch. Once keyrings are ready, I think the best solution to this would be for us to create a `MultiKeyring`[1] variant that calls all child keyrings in parallel.

I can't promise a timeline for this, but if you have a timeline when *you* would need something like this, knowing what that is would help us in our prioritization efforts.

**NOTE: The below should work, but gets into the weeds of how some of the specific components work today.**

If you wanted to do something similar yourself in the meantime, what I would recommend would be to make something that looks like the `DefaultCryptoMaterialsManager`[2] but on calls to `get_encryption_materials`, rather than iterating through each master key sequentially[3][4], it generates with the primary master key[5], then spins off a separate thread for each additional master key[6] and collects all of the encrypted data keys.

If you do this, I would recommend *not* subclassing from `DefaultCryptoMaterialsManager` because we are going to need to change some of the internal behavior of that class as part of building out the keyring support.
I would recommend duplicating the encrypt path logic, and either making an internal instance of `DefaultCryptoMaterialsManager` and passing through to that on decrypt or simply throwing a `NotImplementedError` in `decrypt_materials`.

[1] https://github.com/aws/aws-encryption-sdk-python/blob/keyring/src/aws_encryption_sdk/keyring/multi_keyring.py
[2] https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/materials_managers/default.py
[3] https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/materials_managers/default.py#L87-L92
[4] https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/internal/utils/__init__.py#L98-L129
[5] https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/internal/utils/__init__.py#L114
[6] https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/internal/utils/__init__.py#L119-L122

**Comment by lfdesousa** [comment]
Hi @mattsb42-aws , thanks a lot for this, if there is a possibility of increasing the priority on your side, I will reach out internally since we have opened a case with AWS Premium Support.
I will make sure, that we attach this information to the case so that we can have at least a bit of traction.
For obvious reasons, I can't disclose the case ID here, but if you have any questions, please do not hesitate in reaching out to me.
@polamayster thanks a lot for taking the time to open the issue here.
Thanks!

**Comment by polamayster** [comment]
Hi @mattsb42-aws, I would really appreciate if you could please shed some light on readiness of `keyring` branch in context of this issue or perhaps provide some even vague timeline.
Not sure, but still, maybe we can contribute somehow to speed things up, as we do not want do develop throw away(no official) solution on a background.

**Comment by mattsb42-aws** [comment]
Hi @polamayster, this is currently on our roadmap for 2020Q1 for official release. If this will cause issues for your timelines, please reach out to AWS Crypto Tools through AWS customer support and we can discuss options.

**Comment by lfdesousa** [comment]
Hi there, it has been quite a while since we have not looked at this.
Just asking around how this is progressing?
Thanks,
Luis

**Comment by antonf-amzn** [comment]
Hi, @lfdesousa 

Thank you for your patience.  Urgent issues changed our 2020 roadmap and required a re-evaluation of our schedule.  Keyrings for Python remains a priority for our team for 2021.  Please stay tuned for an update, and please let us know in the meantime here or via AWS Support if there’s anything new from your side that we should know.  

Once again, apologies for not communicating changes to our roadmap earlier.
