### ISSUE TITLE
No documentation (or implementation?) for using grants

### ISSUE THREAD

**Issue by mb941** [aws/aws-encryption-sdk-python#315]
I need to encrypt a large file, however, the KMS CMK I need to encrypt the file with I only have access to via a KMS grant.
There doesn't seem to be any documentation on how to achieve this and after a search through the code base I could find very little mention of grants (however, my python isn't the strongest).

How do I go about this? I assume I need to provide the grant token to a Key Provider, as that seems to be the component doing the actual interface with KMS, but don't know which one or how.

**Comment by farleyb-amazon** [comment]
Hi mb941,

You generally don't need to pass grants to KMS in order to use them; they will take effect even if you don't pass the grant tokens. The only exception to this is if you are depending on the grant permissions to take effect immediately after creating the grant. Because grant creation is eventually consistent, if you are creating the grant and then immediately trying to use it, it can be useful to pass the grant token to the call. You can check out the [KMS documentation on grants](https://docs.aws.amazon.com/kms/latest/developerguide/grants.html#about-grants) for more details.

All that said, if you do need to provide grant tokens for use with the encryption SDK you can do so with a [`KMSMasterKey`](https://aws-encryption-sdk-python.readthedocs.io/en/latest/generated/aws_encryption_sdk.key_providers.kms.html#aws_encryption_sdk.key_providers.kms.KMSMasterKey), which lets you specify grant tokens that should be passed to KMS. So you can create a `KMSMasterKey` with the appropriate grant tokens, then add it to your master key provider. Something like:

```
key = KMSMasterKey(key_id="your-key-id", grant_tokens=[grant_token_1, grant_token_2])
key_provider.add_master_key_provider(key)
```

We'll look into improving our documentation to make this use case more clear.

**Comment by mb941** [comment]
Hi Ben,

Thanks very much for your response, this looks like what I'm after! We didn't want to hang around for eventual consistency as we wanted to keep the grants as short lived as possible. I did a little more digging after posting this originally and was worried I was going to have to wait for the new keyring implementation to be completed. Glad this is available currently.
