### ISSUE TITLE
Getting aws encryption sdk error in our Jenkins build while trying to decrypt your .crt file 

### ISSUE THREAD

**Issue by Pervej-Alam** [aws/aws-encryption-sdk-python#493]
Hi Team
Below aws encryption sdk error in our Jenkins build while trying to decrypt your .crt file  , Need assistance to resolve the Issue.

Error:-
>> Not Supported Error Unsupported version 45", "45 is not a valid SerializationVersion"

Regards,
Pervej

**Comment by texastony** [comment]
Howdy @Pervej-Alam,

> while trying to decrypt your .crt file

The AWS Encryption SDK (ESDK) does not author crt files.
It authors encrypted messages.

Most of the time, it is up to the encrypting party to serialize these encrypted messages.
Though the AWS Encryption SDK CLI (ESDK-CLI) can directly serialize messages,
it is up to the encrypting party to determine the file suffix.

The `NotSupportedError` raised indicates that the date being read
cannot be deserialized into a known encrypted message format.

Are you certain that a variant of the ESDK wrote the message
you are trying to decrypt?

Could it be that another Amazon Encryption product produced this message?

Or was some other transform applied to the encrypted message?

If you can confirm that the an ESDK wrote this message,
please share with us a code snippet or instructions that we can use
to reproduce this issue.

Otherwise, I believe your best path to resolve this issue is
to work with the author of these encrypted messages;
validating that they are encrypted with an ESDK and that any
post encryption transforms are appropriately reversed prior to decryption.

Much Obliged,
AWS Crypto Tools

**Comment by lavaleri** [comment]
Closing this issue for now. @Pervej-Alam if you have follow up or clarification here please feel free to reopen this issue and we can help you with your issue.
