### ISSUE TITLE
Does AWS Encryption SDK support AES256 encryption/decryption and SHA256 checksum calculation?

### ISSUE THREAD

**Issue by snowuyl** [aws/aws-encryption-sdk-python#514]
I need AES256 encryption/decryption to encrypt/decrypt static data and SHA256 checksum calculation for checking transmitting completeness. Does AWS Encryption SDK support AES256 encryption/decryption and SHA256 checksum calculation?

**Comment by ajewellamz** [comment]
Can you clarify your use case?

If you’re just using the SDK, it performs envelope encryption, which can encrypt using AES-256-GCM, and includes a signature that authenticates the message. See https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/concepts.html#envelope-encryption

If you’re trying to interface with another crypto library, we don’t interface with other crypto libraries because of our unique format, but we’d like to know your requirements. Why these primitives, specifically? What is this other library expecting? What exactly do you mean by AES256, is it AES-256-GCM, AES-256-CBC or something else?

We do not support AES-256-CBC encryption, and we do not support SHA256 checksums.

**Comment by lavaleri** [comment]
Closing this issue for now. @snowuyl if you have follow up or clarification here please feel free to reopen this issue and we can help answer your question.
