### ISSUE TITLE
Can't pass an object with read() to StreamDecryptor

### ISSUE THREAD

**Issue by Redoubts** [aws/aws-encryption-sdk-python#75]
So now I'm trying to download an encrypted file, and I figured I'd pipe it through the `StreamDecryptor`. But when I try this, I get back 

`TypeError: 'StreamingBody' does not have the buffer interface`

I suspect this is because in `def prep_stream_data(data):` (L138:internal/utils/\_\_init\_\_.py), my file like object is checked with `isinstance(data, (file, io.IOBase, six.StringIO))`. But my object is a botocore `StreamingBody`, which doesn't inherit from any of these. So my object gets passed to io.BytesIO and dies because it's a stream and not a buffer.

I'm not sure what this check is specifically requiring, it might be nicer to check for specific methods -- I expected anything with `read()` to work here.

**Comment by mattsb42-aws** [comment]
I think the simplest solution to this is to invert what `prep_stream_data` is doing and rather than pass through stuff that matches a certain pattern, instead pass through anything that is not a string or bytes, and cast/wrap those.

We'll probably want to change this in the future to be more prescriptive, but before that I'll want to properly define what API we expect source streams to have and expose a helper to check that.

**Comment by mattsb42-aws** [comment]
This fix is now available in version `1.3.6`.

**Comment by mattsb42-aws** [comment]
This fix is now available in version `1.3.6`.
